# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create email: 'lhm1442@gmail.com', password: '111111', name: '이현민', id: '1', status: '5', photo: 'http://apsurvey.co.kr/secretlion/lhm.png'
User.create email: 'jg0428.lim@gmail.com', password: '111111', name: '임정건', id: '2', status: '5', photo: 'http://apsurvey.co.kr/secretlion/ijg.png'
User.create email: 'uk6342@gmail.com', password: '111111', name: '서동욱', id: '3', status: '5', photo: 'http://apsurvey.co.kr/secretlion/sdw.png'
User.create email: 'rr5ys5s@gmail.com', password: '111111', name: '박승환', id: '4', status: '5', photo: 'http://apsurvey.co.kr/secretlion/pseungh.png'
User.create email: 'rlaxodhksk@naver.com', password: '111111', name: '김태완', id: '5', status: '5', photo: 'http://apsurvey.co.kr/secretlion/ktw.png'
User.create email: 'kimkyungdo08@gmail.com', password: '111111', name: '김경도', id: '6', status: '5', photo: 'http://apsurvey.co.kr/secretlion/kkd.png'
User.create email: 'namhk5741@likelion.org', password: '111111', name: '남형걸', id: '7', status: '5', photo: 'http://apsurvey.co.kr/secretlion/nhg.png'
User.create email: 'kim90@likelion.org', password: '111111', name: '김근영', id: '8', status: '5', photo: 'http://apsurvey.co.kr/secretlion/kky.png'
User.create email: 'nm5005@snu.ac.kr', password: '111111', name: '조정원', id: '9', status: '5', photo: 'http://apsurvey.co.kr/secretlion/jjw.png'
User.create email: 'jyoonsong@likelion.org', password: '111111', name: '송재윤', id: '10', status: '5', photo: 'http://apsurvey.co.kr/secretlion/sjy.png'
User.create email: 'pjhjohn@gmail.com', password: '111111', name: '박준호', id: '11', status: '5', photo: 'http://apsurvey.co.kr/secretlion/pjh.png'
User.create email: 'cokr3430@gmail.com', password: '111111', name: '정유철', id: '12', status: '5', photo: 'http://apsurvey.co.kr/secretlion/jyc.png'
User.create email: 'rlarnjsqhd@gmail.com', password: '111111', name: '김권봉', id: '13', status: '5', photo: 'http://apsurvey.co.kr/secretlion/kkb.png'
User.create email: 'dongmin.shin@dm.snu.ac.kr', password: '111111', name: '신동민', id: '14', status: '5', photo: 'http://apsurvey.co.kr/secretlion/sdm.png'
User.create email: 'yoonhy557@gmail.com', password: '111111', name: '윤현영', id: '15', status: '5', photo: 'http://apsurvey.co.kr/secretlion/yhy.png'
User.create email: 'spacesailormh@gmail.com', password: '111111', name: '이문환', id: '16', status: '5', photo: 'http://apsurvey.co.kr/secretlion/lmh.png'
User.create email: 'eckim09@gmail.com', password: '111111', name: '김은총', id: '17', status: '5', photo: 'http://apsurvey.co.kr/secretlion/kec.png'
User.create email: 'chaosphch@gmail.com', password: '111111', name: '정현우', id: '18', status: '5', photo: 'http://apsurvey.co.kr/secretlion/jhw.png'
User.create email: 'ecardin@snu.ac.kr', password: '111111', name: '조성래', id: '19', status: '5', photo: 'http://apsurvey.co.kr/secretlion/jsr.png'
User.create email: '07js23@gmail.com', password: '111111', name: '서재성', id: '20', status: '5', photo: 'http://apsurvey.co.kr/secretlion/sjs.png'
User.create email: 'taekeongo@gmail.com', password: '111111', name: '고태건', id: '21', status: '5', photo: 'http://apsurvey.co.kr/secretlion/ktg.png'
User.create email: 'zmfl156@snu.ac.kr', password: '111111', name: '이윤성', id: '22', status: '5', photo: 'http://apsurvey.co.kr/secretlion/lys.png'
User.create email: 'opera5@snu.ac.kr', password: '111111', name: '채경완', id: '23', status: '5', photo: 'http://apsurvey.co.kr/secretlion/cgw.png'
User.create email: 'worhee421@gmail.com', password: '111111', name: '손원희', id: '24', status: '5', photo: 'http://apsurvey.co.kr/secretlion/swh.png'
User.create email: '0706gusl@gmail.com', password: '111111', name: '조현', id: '25', status: '5', photo: 'http://apsurvey.co.kr/secretlion/jh.png'
User.create email: 'shaircast@gmail.com', password: '111111', name: '박성환', id: '26', status: '5', photo: 'http://apsurvey.co.kr/secretlion/psungh.png'
User.create email: 'sualyer010@gmail.com', password: '111111', name: '구자운', id: '27', status: '5', photo: 'http://apsurvey.co.kr/secretlion/kjw.png'
User.create email: 'humblekim0709@gmail.com', password: '111111', name: '김은수', id: '28', status: '5', photo: 'http://apsurvey.co.kr/secretlion/kes.png'
User.create email: 'kimtitu@snu.ac.kr', password: '111111', name: '김유경', id: '29', status: '5', photo: 'http://apsurvey.co.kr/secretlion/kyg.png'
User.create email: 'forestrainee@gmail.com', password: '111111', name: '임비', id: '30', status: '5', photo: 'http://apsurvey.co.kr/secretlion/ib.png'
User.create email: 'jhroh906@gmail.com', password: '111111', name: '노준현', id: '31', status: '5', photo: 'http://apsurvey.co.kr/secretlion/njh.png'
User.create email: 'kyoendoo@gmail.com', password: '111111', name: '김연두', id: '32', status: '5', photo: 'http://apsurvey.co.kr/secretlion/kyd.png'
User.create email: 'zkmm234@gmail.com', password: '111111', name: '이재성', id: '33', status: '5', photo: 'http://apsurvey.co.kr/secretlion/ljs.png'
User.create email: 'alex1381@naver.com', password: '111111', name: '김승현', id: '34', status: '5', photo: 'http://apsurvey.co.kr/secretlion/ksh.png'
User.create email: 'coals1153@gmail.com', password: '111111', name: '임채민', id: '35', status: '5', photo: 'http://apsurvey.co.kr/secretlion/icm.png'
User.create email: 'j4159804@naver.com', password: '111111', name: '정정수', id: '36', status: '5', photo: 'http://apsurvey.co.kr/secretlion/jjs.png'
User.create email: 'hyunsujeong@snu.ac.kr', password: '111111', name: '정현수', id: '37', status: '5', photo: 'http://apsurvey.co.kr/secretlion/jhs.png'
